services:
  # Client Service
  client:
    image: micro_service/client
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - posts  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://client:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Posts Service
  posts:
    image: micro_service/posts
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - comments  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://posts:4000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Comments Service
  comments:
    image: micro_service/comments
    ports:
      - "4001:4001"
    networks:
      - app-network
    depends_on:
      - moderation  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://comments:4001"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Query Service
  query:
    image: micro_service/query
    ports:
      - "4002:4002"
    networks:
      - app-network
    depends_on:
      - posts   
    healthcheck:
      test: ["CMD", "curl", "-f", "http://query:4002"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Moderation Service
  moderation:
    image: micro_service/moderation
    ports:
      - "4003:4003"
    networks:
      - app-network
    depends_on:
      - event-bus  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://moderation:4003"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Event-Bus Service
  event-bus:
    image: micro_service/event-bus
    ports:
      - "4005:4005"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://event-bus:4005"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Docker Registry Service
  registry:
    image: registry:2
    ports:
      - "5005:5000"
    volumes:
      - ./data:/var/lib/registry
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://registry:5000/v2/_catalog"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  app-network:
    driver: bridge
