apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus-srv
  template:
    metadata:
      labels:
        app: event-bus-srv
    spec:
      containers:
      - name: event-bus-srv
        image: micro_service/event-bus
        ports:
        - containerPort: 4005
