apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation-srv
  template:
    metadata:
      labels:
        app: moderation-srv
    spec:
      imagePullSecrets:
        - name: regcred  
      containers:
      - name: moderation-srv
        image: localhost:5000/micro_service/moderation
        imagePullPolicy: Always
        ports:
        - containerPort: 4003
