apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-srv
  template:
    metadata:
      labels:
        app: posts-srv
    spec:
      containers:
      - name: posts-srv
        image: localhost:5001/micro_service/posts
        ports:
        - containerPort: 4000