apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-clusterip-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-clusterip-srv
  template:
    metadata:
      labels:
        app: posts-clusterip-srv
    spec:
      containers:
      - name: posts-clusterip-srv
        image: micro_service/posts
        ports:
        - containerPort: 4000
